services:
  node:
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
    ports:
      - "80:3000"
    tty: true
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-northeast-1
      - SERVERLESS_SERVICE_NAME=${SERVERLESS_SERVICE_NAME}